# Kibana is served by a back end server. This controls which port to use.
port: 5601

# The host to bind the server to.
host: "0.0.0.0"

# The Elasticsearch instance to use for all your queries.
elasticsearch_url: "http://localhost:9200"

# preserve_elasticsearch_host true will send the hostname specified in `elasticsearch`. If you set it to false,
# then the host you use to connect to *this* Kibana instance will be sent.
elasticsearch_preserve_host: true

# Kibana uses an index in Elasticsearch to store saved searches, visualizations
# and dashboards. It will create a new index if it doesn't already exist.
kibana_index: ".kibana"

# If your Elasticsearch is protected with basic auth, this is the user credentials
# used by the Kibana server to perform maintence on the kibana_index at statup. Your Kibana
# users will still need to authenticate with Elasticsearch (which is proxied thorugh
# the Kibana server)
# kibana_elasticsearch_username: user
# kibana_elasticsearch_password: pass

# If your Elasticsearch requires client certificate and key
# kibana_elasticsearch_client_crt: /path/to/your/client.crt
# kibana_elasticsearch_client_key: /path/to/your/client.key

# If you need to provide a CA certificate for your Elasticsarech instance, put
# the path of the pem file here.
# ca: /path/to/your/CA.pem

# The default application to load.
default_app_id: "discover"

# Time in milliseconds to wait for elasticsearch to respond to pings, defaults to
# request_timeout setting
# ping_timeout: 1500

# Time in milliseconds to wait for responses from the back end or elasticsearch.
# This must be > 0
request_timeout: 300000

# Time in milliseconds for Elasticsearch to wait for responses from shards.
# Set to 0 to disable.
shard_timeout: 0

# Time in milliseconds to wait for Elasticsearch at Kibana startup before retrying
# startup_timeout: 5000

# Set to false to have a complete disregard for the validity of the SSL
# certificate.
verify_ssl: true

# SSL for outgoing requests from the Kibana Server (PEM formatted)
# ssl_key_file: /path/to/your/server.key
# ssl_cert_file: /path/to/your/server.crt

# Set the path to where you would like the process id file to be created.
# pid_file: /var/run/kibana.pid

# If you would like to send the log output to a file you can set the path below.
# This will also turn off the STDOUT log output.
# log_file: ./kibana.log

# These settings control the OAuth access control layer.  By default this is
# disabled.  If you wish to enable it, you will need an OAuth provider which
# supports the following endpoint:
#
# GET /permissions/{statistics_permission_name}
#
# This should return a JSON document of the form {"permitted": true/false}, to
# authenticate the logged-in user against the given permission.
#
# To use OAuth access control, you need to set up a Redis server to store user
# sessions (see below).
#
# Required values left uncommented, default values provided.
oauth:
  # Set to true to enable OAuth access control
  # enabled: false

  # The OAuth scope to request access to
  # scope: "access:permissions"

  # The permission name to request to view statistics on Kibana
  # statistics_permission_name: "viewstatistics"

  # The following are all required values
  # (Required) The client ID given to you by your OAuth provider
  client_id: ""

  # (Required) The client secret given to you by your OAuth provider
  client_secret: ""

  # (Required) The base URL of your OAuth provider
  site: ""

  # The token endpoint for your OAuth provider
  # token_path: "/oauth/token"

  # The authorization endpoint for your OAuth provider
  # authorization_path: "/oauth/authorize"

  # (Required) The base URL for the permissions API
  api_url: ""

  # (Required) If Kibana is running behind a firewall or reverse-proxy, this is
  # the external URL from whicn you can access Kibana.  This is used to build
  # OAuth redirect URLs.  For development purposes this will likely be
  # "http://localhost:5601".
  external_url: ""

# These settings are for storing user sessions in Redis.  They are only used if
# OAuth access control is enabled.
#
# Required values left uncommented, default values provided.
session:
  # The host of your Redis server.
  # redis_host: "localhost"

  # The port of your Redis server
  # redis_port: 6379

  # The prefix for storing session keys
  # redis_prefix: "kibana4:sess:"

  # (Required) A secret to encrypt session keys with
  secret: ""
